default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fer_dev
  host: localhost
  port: 5432
  username: postgres
  password: 123mudar@
test:
  <<: *default
  database: ieat_test

production:
  <<: *default
  database: ieat_production
  username: ieat
  password: <%= ENV['IEAT_DATABASE_PASSWORD'] %>
